
common: &common
  adapter: postgresql
  encoding: unicode
  username: www
  password: www
  pool: 5

development:
  <<: *common
  database: dm_dev

test:
  <<: *common
  database: dm_test

production:
  <<: *common
  database: dm_prod
